tests: do not assume that the eth interface is named eth0

diff --git a/tests/full/correct-dns-setup/task.yaml b/tests/full/correct-dns-setup/task.yaml
--- a/tests/full/correct-dns-setup/task.yaml
+++ b/tests/full/correct-dns-setup/task.yaml
@@ -6,18 +6,17 @@ execute: |
         0)
             # For correct timing if the device has just booted
             wait_for_network_manager
+            get_qemu_eth_iface eth_if
 
             # Precondition is a existing network connection
-            /snap/bin/network-manager.nmcli d | grep 'eth0.*connected'
+            /snap/bin/network-manager.nmcli d | grep "$eth_if.*connected"
 
-            # We get a default nameserver from the gateway
-            if [ "$SPREAD_BACKEND" = "qemu" ] ; then
-                cat /etc/resolv.conf | grep 'nameserver 10.0.2.3'
-            fi
+            # Make sure some namserver has been specified in resolv.conf
+            cat /etc/resolv.conf | grep 'nameserver'
 
             # Ensure we can resolve a hostname correctly; must give a
             # valid IP address
-            address=`python3 -c 'import socket; print(socket.gethostbyname("ubuntu.com"))'  2> /dev/null || echo "invalid"`
+            address=$(python3 -c 'import socket; print(socket.gethostbyname("ubuntu.com"))' 2> /dev/null || echo "invalid")
             [ "$address" != "invalid" ] && [[ $address =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]
 
             # Now lets switch to a system where we have a configuration
@@ -26,7 +25,7 @@ execute: |
             REBOOT
             ;;
         1)
-            /snap/bin/network-manager.nmcli d | grep 'eth0.*connected'
+            /snap/bin/network-manager.nmcli d | grep "$eth_if.*connected"
             /snap/bin/network-manager.nmcli d | grep -v netplan
 
             connection=$(/snap/bin/network-manager.nmcli -m multiline -f UUID c show --active | awk '{print$2;exit}')
